### PR TITLE
Update _processMime wrapper to match the original method again

### LINKED ISSUE #10: No longer works with Anki 2.1.36beta2
https://forums.ankiweb.net/t/anki-2-1-36-beta/3893/13

This will produce an error when using ctrl+v in the add card dialog. The link above has a discussion on the error produced and where the code was changed so that you can make a quick update.

Thanks!

### PR DESCRIPTION
**Pull request by zjosua**
Fixes #10

https://forums.ankiweb.net/t/anki-2-1-36-beta/3893/14

### CODE REVIEW

**Comment by searene** [comment]
Thanks for the pull request, but adding it seems to cause incompatibilites on older versions of Anki. I tested it on Anki 2.1.26 and got the following error message:

```
TypeError: _processMime_around() missing 1 required positional argument: 'extended'
```

Maybe there is a better way to do this.

**Comment by zjosua** [comment]
Ankiweb accepts multiple "builds" per add-on to be uploaded.
Just tell ankiweb to use this version (with the required "extended" argument) of the add-on only with Anki version 2.1.36 or higher.
The current version of the add-on will still be available and automatically used for older versions of Anki.

**Review by searene — APPROVED** [review]
